config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :wishlists, only: [:create]
  end

  root to: "pages#home"

  resources :exchanges, only: [:show, :update] do
    resources :messages, only: :create
    member do
      post :complete_exchange
    end
  end

  resources :vinyls, only: [:index, :show] do
    # resources :exchanges, only: [:index]
    # resources :collections_vinyls, only: [:create, :new] # Ceci sont les anciennes routes, il faudrait prendre ceux de users_vinyls à la place
    resources :users_vinyls, only: [:create, :new, :update]
  end

  resources :collections, only: [:new, :create, :show, :index]

  resources :collections_vinyls, only: [:destroy]

  resources :users_vinyls, only: [] do
    resources :exchanges, only: [:new, :create]
    resources :collections_vinyls, only: [:create]
  end

  resources :wishlists, only: [:destroy]

  get "my-exchanges", to: "exchanges#index"
  patch "exchanges/:id/status", to: "exchanges#update_status"
  patch "exchanges/:id/offered_vinyl", to: "exchanges#update_offered_vinyl"
  get "vinyls-to-exchange", to: "collections#vinyls_to_exchange"
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :collections_vinyls
  has_many :users_vinyls, through: :collections_vinyls
  has_many :vinyls, through: :users_vinyls
  has_one_attached :photo
  validates :name, presence: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @vinyls_to_exchange = current_user.vinyls_to_exchange
    @collections_select = current_user.collections.map { |c| [c.name, c.id] }
    @collections = current_user.collections
    @users_vinyls = current_user.users_vinyls.includes(:vinyl)
    @collections_vinyl = CollectionsVinyl.new

    if params[:query].present?
      @users_vinyls = UsersVinyl.search_by_title_and_year(params[:query])
    else
      # page d'accueil vide
      @users_vinyls.all
    end

  end

  def show
    @collection = Collection.find(params[:id])
    # @collection_vinyl = CollectionVinyl.where(collection_id: @collection)
  end

  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    if @collection.save
      redirect_to collections_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def collection_params
    params.require(:collection).permit(:name, :user_id, :photo)
  end
end

app/views/collections/_collection.html.erb
<div class="card" style="width: 18rem;">
      <%= cl_image_tag collection.photo.key %>
      <div class="card-body">
        <h5 class="card-title"><%= collection.name %></h5>
      </div>
</div>

app/views/collections/_form.htnl.erb
<%= simple_form_for(@collection) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-inputs">
    <%= f.input :photo, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <% end %>

app/views/collections/_list_form.html.erb
<div class="dropstart dropup list-form">
  <button class="btn btn-info btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
  </button>
  <ul class="dropdown-menu form-style">
    <%= simple_form_for([user_vinyl, @collections_vinyl]) do |f| %>
      <%=f.input :collection_id, as: :radio_buttons, collection: @collections_select, label: ""%>
      <%= f.submit class: "form-style btn btn-info", value: "Valider"%>
    <% end %>

  </ul>
</div>

app/views/collections/index.html.erb
<div class="text-center p-5" style="background-color: #FAC066">
  <h2>Vous avez <%= @users_vinyls.count %> vinyles dans votre collection </h2>
</div>

<div class="container">
  <div class="d-flex align-items-center mt-3">
    <i class="fa-solid fa-arrow-left"></i>
    <a><%= link_to "Retour", vinyls_path, class: "btn btn-retour " %></a>
  </div>
</div>

<div class="container">

  <div class="d-flex justify-content-center">
    <div class="simple_form search w-50 mt-4 mb-4 text-center">
      <%= form_with url: collections_path, method: :get, class: "d-flex search-form-control form-group" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control string required ",
            placeholder: "Recherche un vinyle..."
            %>
            <%= submit_tag "Soumettre", class:"button" %>
      <% end %>
    </div>
  </div>

  <div data-controller ="onglet">
      <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
          <button  data-onglet-target = "all"
                  data-action="click->onglet#all"
                  class="nav-link active tab"
                  id="nav-home-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#nav-home"
                  type="button" role="tab"
                  aria-controls="nav-home"
                  aria-selected="true">Mes vinyles</button>

          <button data-onglet-target="playlist"
                  data-action="click->onglet#playlist"
                  class="nav-link"
                  id="nav-profile-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#nav-profile"
                  type="button"
                  role="tab"
                  aria-controls="nav-profile"
                  aria-selected="false">Mes listes</button>

          <button data-onglet-target="echange"
                  data-action="click->onglet#echange"
                  class="nav-link"
                  id="nav-contact-tab"
                  data-bs-toggle="tab"
                  data-bs-target="#nav-contact"
                  type="button"
                  role="tab"
                  aria-controls="nav-contact"
                  aria-selected="false">Mes vinyles à échanger</button>
      </div>
    </nav>


  <div  class= "container mt-4 mb-4">
    <div class="row row-cols-1 row-cols-md-4 g-4">
      <% @users_vinyls.each do |user_vinyl|%>
        <div class="col">

          <div class="card shadow" data-onglet-target="cards">
              <%= image_tag (user_vinyl.vinyl.photo_url), class:"vinyl_image"%>
            <div class="text px-4 pb-4 flex-fill">
              <div class="vinyl-title">
                <p class="fw-bold m-0"><%= user_vinyl.vinyl.title %></p>
              </div>
              <p class="description">
                <%= user_vinyl.vinyl.artist.name %>, <em><%= user_vinyl.vinyl.year %></em>
              </p>
              <div class="d-flex justify-content-between align-items-center w-100">

                <div data-controller="user-vinyl">
                  <%= simple_form_for([user_vinyl.vinyl, user_vinyl], html: { data: { "user-vinyl-target": "form" } }) do |f| %>
                    <div class="switch-checkbox">
                      <%= f.input :offer_for_trade, label: "<span></span>".html_safe, input_html: { id: "offer-for-trade-#{user_vinyl.id}", data: { action: "change->user-vinyl#changeOfferForTrade" } }%>
                    </div>
                  <% end %>
                </div>

                <%= render "list_form", user_vinyl: user_vinyl %>

              </div>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>


  <div class="container">
    <div class="cards">

      <% if @vinyls_for_exchange %>
        <div class="card-category m-3 d-none" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3))">
          <a><%= link_to 'Pour Echanger', vinyls_to_exchange_path %>
        </div>
      <% end %>


      <% @collections.each do |collection| %>
          <div data-onglet-target="collections" class="card-category m-3 d-none" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(collection.photo.key) if collection.photo.attached? %>)">
            <a><%= link_to collection.name, collection %>
          </div>
        <% end %>
      <div data-onglet-target="collections" class="d-none"><%= link_to "+", new_collection_path, class: "buton-add m-3"%></div>
    </div>
  </div>


  <div class="container">

    <div class= "mt-4 mb-4">
      <div class="row row-cols-1 row-cols-md-4 g-4">
        <% @vinyls_to_exchange.each do |to_exchange| %>
          <div class="col">
            <div data-onglet-target="echanges" class="card shadow d-none">
              <div><%= image_tag (to_exchange.photo_url), class:"vinyl_image" %></div>
              <div class="text px-4 pb-4 flex-fill">

                  <div class="vinyl-title">
                  <p class="fw-bold m-0">
                  <%= to_exchange.title%>
                  </p>
                  </div>
                  <p>
                  <%= to_exchange.artist.name%>, <em><%=to_exchange.year%></em>
                  </p>
              </div>


            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/collections/new.html.erb
<div class="head">
<div class="text-center p-5" style="background-color: #FAC066">
  <h1>Nouvelle Collection</h1>
</div>

<div class="container">
  <div class="d-flex align-items-center mt-3">
    <i class="fa-solid fa-arrow-left"></i>
    <a><%= link_to "Retour", vinyls_path, class: "btn btn-retour " %></a>
  </div>
</div>

  <div class="container py-5">
    <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
        <div class="bg-white rounded p-3 shadow">

          <%= simple_form_for(@collection) do |f| %>
            <%= f.error_notification %>
              <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <div class="form-inputs">
                  <%= f.input :name, label: "Nom" %>
                </div>
                <div class="form-inputs">
                  <%= f.input :photo, as: :file %>
                </div>
                <div class="form-actions">
                  <%= f.button :submit, class: "btn btn-info", value: "Créer"  %>
                </div>
          <% end %>

        </div>
      </div>
    </div>
  </div>

</div>

app/views/collections/show.html.erb
<div class="text-center p-5" style="background-color: #FAC066">
<h1><%=@collection.name%></h1>
</div>
<div class="container">
  <div class="d-flex align-items-center mt-3">
    <i class="fa-solid fa-arrow-left"></i>
    <a><%= link_to "Retour", collections_path, class: "btn btn-retour " %></a>
  </div>
</div>

<div class= "container">
  <div class="row row-cols-1 row-cols-md-4 g-4 mt-2 text px-4 pb-4 flex-fill">
    <% @collection.vinyls.each do |vinyl| %>
    <div class="col">
      <div class ="card shadow">
        <img><%= image_tag (vinyl.photo_url), class:"vinyl_image" %>
        <div class="text p-3 flex-fill">
          <div class="vinyl-title">
            <p class="fw-bold m-0">
              <%= vinyl.title %>
            </p>
          </div>
          <p>
            <%# <strong>Artiste</strong> %>
            <%= vinyl.artist.name %>, <em><%= vinyl.year %></em>
          </p>

        </div>
      </div>
    </div>
    <% end %>

  </div>
</div>

<%# # Afficher le vinyl de la collection  %>

app/views/collections/vinyls_to_exchange.html.erb
<% @vinyls_to_echange.each do |vinyl| %>
  <%= vinyl.collection_vinyl.vinyl.title  %>
<% end %>