config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :wishlists, only: [:create]
  end

  root to: "pages#home"

  resources :exchanges, only: [:show, :update] do
    resources :messages, only: :create
    member do
      post :complete_exchange
    end
  end

  resources :vinyls, only: [:index, :show] do
    # resources :exchanges, only: [:index]
    # resources :collections_vinyls, only: [:create, :new] # Ceci sont les anciennes routes, il faudrait prendre ceux de users_vinyls à la place
    resources :users_vinyls, only: [:create, :new, :update]
  end

  resources :collections, only: [:new, :create, :show, :index]

  resources :collections_vinyls, only: [:destroy]

  resources :users_vinyls, only: [] do
    resources :exchanges, only: [:new, :create]
    resources :collections_vinyls, only: [:create]
  end

  resources :wishlists, only: [:destroy]

  get "my-exchanges", to: "exchanges#index"
  patch "exchanges/:id/status", to: "exchanges#update_status"
  patch "exchanges/:id/offered_vinyl", to: "exchanges#update_offered_vinyl"
  get "vinyls-to-exchange", to: "collections#vinyls_to_exchange"
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :requested_vinyl, class_name: "UsersVinyl", foreign_key: :requested_vinyl_id
  belongs_to :offered_vinyl, class_name: "UsersVinyl", foreign_key: :offered_vinyl_id, optional: true
  has_many :offered_vinyls, dependent: :destroy
  # has_many :collections_vinyls, through: :offered_vinyls
  # has_many :vinyls, through: :collections_vinyls
  has_many :messages, dependent: :destroy

  enum status: {
    pending: 0,
    confirmed: 1,
    rejected: 2
  }

  validates :requested_vinyl, presence: true
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchange, only: [:update, :complete_exchange]

  def index
    @exchanges = current_user.exchanges
    @incoming_exchanges = current_user.incoming_exchanges
    @exchange = Exchange.last
    @message = Message.new
  end

  def show
  end

  def create
    exchange = Exchange.new(requested_vinyl_id: params[:users_vinyl_id], user: current_user, status: :pending)
    exchange.save!
    params[:collection_vinyl_ids].each do |cvid|
      offered_vinyls = OfferedVinyl.new(exchange: exchange, users_vinyl_id: cvid)
      offered_vinyls.save!
    end
    redirect_to my_exchanges_path
    # rescue
    # render :new, status: :unprocessable_entity
  end

  def update
    offered_vinyl = OfferedVinyl.find(exchange_params[:offered_vinyl_id]).users_vinyl
    @exchange.offered_vinyl = offered_vinyl
    if @exchange.save
      redirect_to my_exchanges_path
    else
      render :show, status: :unprocessable_entity
    end
  end

  def new
    @users_vinyls_to_offer = current_user.users_vinyls_to_exchange.includes(:vinyl)
    @requested_vinyl = UsersVinyl.find(params[:users_vinyl_id])
    @exchange = Exchange.new
  end

  def complete_exchange

    requested_users_vinyl = @exchange.requested_vinyl
    offered_users_vinyl = @exchange.offered_vinyl

    requested_users_vinyl.destroy
    offered_users_vinyl.destroy

    UsersVinyl.create(
      user: requested_users_vinyl.user,
      vinyl: offered_users_vinyl.vinyl
    )

    UsersVinyl.create(
      user: offered_users_vinyl.user,
      vinyl: requested_users_vinyl.vinyl
    )
    redirect_to collections_path
  end

  private

  def exchange_params
    params.require(:exchange).permit(:offered_vinyl_id)
  end

  def set_exchange
    @exchange = Exchange.find(params[:id])
  end
end

app/views/exchanges/index.html.erb
<div class="text-center p-5" style="background-color: #FAC066">
 <h2>Commence ton échange</h2>
</div>

  <div class="container">
      <% @exchanges.each do |exchange| %>
        <div class="row d-flex justify-content-center my-5">
            <div class="col-3">
              <div class="card shadow">
                <div>
                  <%= image_tag exchange.requested_vinyl.vinyl.photo_url, class:"vinyl_image" unless exchange.requested_vinyl.nil? %>
                </div>

                <div class="text px-4 pb-4 flex-fill">
                  <div class="vinyl-title">
                    <p class="fw-bold m-0">
                    <%= exchange.requested_vinyl.vinyl.title %>
                    </p>
                  </div>
                  <p>
                    <%= exchange.requested_vinyl.vinyl.artist.name %>, <em><%= exchange.requested_vinyl.vinyl.year %></em>
                  </p>
                </div>
              </div>
            </div>

  <div class="col-3 " style="height: 365px;">
    <div class="d-flex flex-column justify-content-evenly align-items-center h-100">
      <div class="d-flex flex-column align-items-center">
        <% if exchange.offered_vinyl_id.nil? %>
          <p class="w-100text-center m-0">En attente</p>
          <br>
            <div class="text-center">
              <i class="fa-solid fa-rotate fleche-echange"></i>
            </div>
        <% else %>
          <p class="w-75 text-center m-0">Valide cet échange pour mettre à jour ta collection</p>
          <br>
            <div class="text-center">
              <i class="fa-solid fa-rotate fleche-echange"></i>
            </div>
            <%= link_to "Valider", complete_exchange_exchange_path(exchange), data: { turbo_method: :post }, class: "btn btn-info mt-3" %>
        <% end %>
        <button class="openChatBtn btn-chat" onclick="openForm()">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-fill" viewBox="0 0 16 16">
            <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
          </svg>
        </button>
      </div>
    </div>
  </div>

  <div class="col-3">
    <div class="d-flex justify-content-between flex-column">
      <% if exchange.offered_vinyl %>
        <div class="d-flex flex-column">
          <div class="card shadow">
            <div>
              <%= image_tag exchange.offered_vinyl.vinyl.photo_url, class:"vinyl_image" unless exchange.requested_vinyl.nil? %>
            </div>

            <div class="text px-4 pb-4 flex-fill">
              <div class="vinyl-title">
                <p class="fw-bold m-0">
                <%= exchange.offered_vinyl.vinyl.title %>
                </p>
              </div>
                      <p>
                        <%= exchange.offered_vinyl.vinyl.artist.name %>, <em><%= exchange.offered_vinyl.vinyl.year %></em>
                      </p>
                    </div>
                  </div>
                </div>

             <% else %>
                <a
                  data-bs-toggle="collapse"
                  href="#collapseExample-<%= exchange.id %>"
                  role="button"
                  aria-expanded="false"
                  aria-controls="collapseExample-<%= exchange.id %>"
                  class="text-dark"
                >

                <div class="d-flex flex-column">
                  <div class="card shadow">
                    <div>
                     <%= image_tag exchange.offered_vinyls.first.users_vinyl.vinyl.photo_url, class:"vinyl_image" unless exchange.requested_vinyl.nil? %>
                    </div>
                    <div class="text px-4 pb-4 flex-fill">
                      <div class="vinyl-title">
                        <p class="fw-bold m-0">
                        <%= exchange.offered_vinyls.first.users_vinyl.vinyl.title %>
                        </p>
                      </div>
                      <p>
                        <%= exchange.offered_vinyls.first.users_vinyl.vinyl.artist.name %>, <em><%= exchange.offered_vinyls.first.users_vinyl.vinyl.year %></em>
                      </p>
                    </div>
                  </div>
                </div>
                </a>

                <div class="collapse" id="collapseExample-<%= exchange.id %>">
                    <% exchange.offered_vinyls.each do |offered_vinyl| %>
                <div class="d-flex flex-column">
                  <div class="card shadow">
                    <div>
                     <%= image_tag offered_vinyl.users_vinyl.vinyl.photo_url, class:"vinyl_image" unless exchange.requested_vinyl.nil? %>
                    </div>
                    <div class="text px-4 pb-4 flex-fill">
                      <div class="vinyl-title">
                        <p class="fw-bold m-0">
                        <%= offered_vinyl.users_vinyl.vinyl.title %>
                        </p>
                      </div>
                      <p>
                        <%= offered_vinyl.users_vinyl.vinyl.artist.name %>, <em><%= offered_vinyl.users_vinyl.vinyl.year %></em>
                      </p>
                    </div>
                  </div>
                </div>
                  <% end %>
                </div>
              <%end%>
            </div>
          </div>
        </div>
      <%end%>
    </div>

    <%# <h2>Voici les échanges proposés</h2> %>
      <% @incoming_exchanges.each do |incoming_exchange| %>
        <%= simple_form_for(incoming_exchange, data: { turbolinks: false }) do |f| %>
          <p>Veuillez selectionner un vinyl</p>
            <div class="card p-3">
              <%= f.association :offered_vinyl, as: :radio_buttons, collection: incoming_exchange.offered_vinyls, label: "", label_method: lambda { |offered_vinyl| "
                  #{image_tag offered_vinyl.users_vinyl.vinyl.photo_url, class:"vinyl_image mb-2" unless incoming_exchange.requested_vinyl.nil?}
                  <p>#{offered_vinyl.users_vinyl.vinyl.title}</p>
                  <p>#{offered_vinyl.users_vinyl.vinyl.year}</p>
                  ".html_safe }
              %>
              <%= f.submit "Valider", class:"btn btn-info mt-3" %>
            </div>
              <% end %>
            <button class="openChatBtn btn-chat" onclick="openForm()">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-fill" viewBox="0 0 16 16">
                <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
              </svg>
            </button>
              <% end %>

        <div class="container exchange"
          data-controller="exchange-subscription"
          data-exchange-subscription-exchange-id-value="<%= @exchange.id %>"
          data-exchange-subscription-current-user-id-value="<%= current_user.id %>"
        >
        <div class ="openChat p-3">
          <h2><%= @exchange.user.first_name != current_user.first_name ? @exchange.user.first_name : @exchange.requested_vinyl.user.first_name.capitalize %></h2>
            <div class="messages"
              id="myForm"
              data-exchange-subscription-target="messages">
                <% @exchange.messages.each do |message| %>
                  <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start'%>">
                    <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
                      <%= render "messages/message", message: message %>
                    </div>
                  </div>
                <% end %>
            </div>

            <%= simple_form_for [@exchange, @message],
              html: {data: {action: "turbo:submit-end->exchange-subscription#resetForm"}, class: "d-flex"} do |f|%>
                <%= f.input :content,
                  label: false,
                  placeholder: "Message ##{@exchange.user.first_name}",
                  wrapper_html: {class: "flex-grow-1"}
                %>
                <%= f.submit "Envoyer", class: "btn btn-info" %>
                  <button type="button"
                          class="btn cancel btn btn-info"
                          onclick="closeForm()"­>fermer
                  </button>
                <% end %>
          </div>

          <script>
          document.querySelector(".openChatBtn") .addEventListener("click", openForm);
          document.querySelector(".close").addEventListener("click", closeForm);
          function openForm() {
              document.querySelector(".openChat").style.display = "block";
              document.querySelector(".messages").scrollTo(0, 2000000000)
          }
          function closeForm() {
              document.querySelector(".openChat").style.display = "none";
            }
          </script>


          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-body" id="exampleModalLabel">Un nouveau vinyle vient d'entrer dans ta collection</h5>
                </div>

              <div class="modal-footer">
                <button type="button" class="btn btn-info mt-3" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>


        <script>
          var myModal = document.getElementById('myModal')
          var myInput = document.getElementById('myInput')

          myModal.addEventListener('shown.bs.modal', function () {
            myInput.focus()
          })
        </script>

app/views/exchanges/new.html.erb
  <div class="text-center p-5" style="background-color: #FAC066">
    <h2>Choisis le(s) vinyle(s) en échange</h2>
  </div>
<div  class="container">
  <div class="d-flex align-items-center mt-3">
    <i class="fa-solid fa-arrow-left"></i>
    <a><%= link_to "Retour", vinyls_path, class: "btn btn-retour " %></a>
  </div>

  <%= simple_form_for([@requested_vinyl, @exchange]) do |v| %>

  <div class= " mt-4 mb-4">

    <div class="row row-cols-1 row-cols-md-4 g-4">
      <% @users_vinyls_to_offer.each do |users_vinyl| %>
        <div class="col">
          <div class="card shadow p-3">
            <label>
              <img><%= image_tag users_vinyl.vinyl.photo_url, class:"card-img-top p-2 " %>
              <div class="ps-2">
                <h5 class="card-title"><%= users_vinyl.vinyl.title%></h5>
                <p class="description"><%=users_vinyl.vinyl.artist.name%>,<%= users_vinyl.vinyl.year %></p>
                <input type="checkbox" name="collection_vinyl_ids[]" value="<%= users_vinyl.id %>">
              </div>
            </label>
          </div>
        </div>
      <% end %>
    </div>
    <div class="form-actions">
      <%= v.button :submit, class: "btn btn-info mt-5 px-3", value: "Valider" %>
    </div>
  <% end %>
  </div>
</div>