config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :wishlists, only: [:create]
  end

  root to: "pages#home"

  resources :exchanges, only: [:show, :update] do
    resources :messages, only: :create
    member do
      post :complete_exchange
    end
  end

  resources :vinyls, only: [:index, :show] do
    # resources :exchanges, only: [:index]
    # resources :collections_vinyls, only: [:create, :new] # Ceci sont les anciennes routes, il faudrait prendre ceux de users_vinyls à la place
    resources :users_vinyls, only: [:create, :new, :update]
  end

  resources :collections, only: [:new, :create, :show, :index]

  resources :collections_vinyls, only: [:destroy]

  resources :users_vinyls, only: [] do
    resources :exchanges, only: [:new, :create]
    resources :collections_vinyls, only: [:create]
  end

  resources :wishlists, only: [:destroy]

  get "my-exchanges", to: "exchanges#index"
  patch "exchanges/:id/status", to: "exchanges#update_status"
  patch "exchanges/:id/offered_vinyl", to: "exchanges#update_offered_vinyl"
  get "vinyls-to-exchange", to: "collections#vinyls_to_exchange"
end

app/models/vinyl.rb
class Vinyl < ApplicationRecord
  belongs_to :artist
  has_many :users_vinyls
  validates :title, presence: true
  validates :year, presence: true, numericality: { only_integer: true }

  include PgSearch::Model
  pg_search_scope :search_by_title_and_year,
    against: [ :title, :year],
    associated_against: {
      artist: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/vinyls_controller.rb
class VinylsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index


    if params[:query].present?
      @vinyls = Vinyl.search_by_title_and_year(params[:query])
    else
      # page d'accueil vide
      @vinyls = Vinyl.order("id DESC").all
    end
  end

  def show
    @vinyl = Vinyl.find(params[:id])
    @users_vinyls = @vinyl.users_vinyls
                          .available_for_trade
                          .without_user(current_user.id)
    # users = @users_vinyls.map { |users_vinyl| users_vinyl.user }
    users_id = @users_vinyls.map { |users_vinyl| users_vinyl.user_id }
    users = User.where(id: users_id)
    @markers = users.geocoded.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(partial: "info_window", locals: { user: user })
      }
    end
  end

  # private

  # def vinyl_params
  #   params.require(:vinyl).permit(:title, :year, :artist_id, :genre_id, :photo_url)
  # end
end

app/views/vinyls/_info_window.html.erb
<h2><%= user.first_name %></h2>
<p><%= user.address %></p>

app/views/vinyls/_vinyl.html.erb
<div class="card shadow">
  <div>
    <%= link_to image_tag(vinyl.photo_url, :class=>"vinyl_image"), vinyl%>
      <%= link_to "+",  vinyl_users_vinyls_path(vinyl, query: params[:query]), class:"button-plus", data: {turbo_method: :post} %>
  </div>

  <div class="text px-4 pb-4 flex-fill">
    <div class="vinyl-title">
      <p class="fw-bold m-0">
        <%= vinyl.title %>
      </p>
    </div>
    <p>
      <%= vinyl.artist.name %>, <em><%= vinyl.year %></em>
    </p>

    <% if vinyl.users_vinyls.available_for_trade.count == 0%>
      <div id="yellow-sentence">
        <i class="fa-solid fa-user-group"></i> Personne ne possède ce vinyle
      </div>
    <%elsif vinyl.users_vinyls.available_for_trade.count == 1 %>
      <div id="yellow-sentence">
        <i class="fa-solid fa-user-group"></i> Une personne possède ce vinyle
      </div>
    <% else %>
      <div id="yellow-sentence">
        <i class="fa-solid fa-user-group"></i> <%=vinyl.users_vinyls.available_for_trade.count%> personnes ont ce vinyle
      </div>

    <%end%>
  </div>
</div>

app/views/vinyls/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://res.cloudinary.com/dvw6upciw/image/upload/v1670444848/adrian-korte-5gn2soeAc40-unsplash_sz9jt7.jpg);">
  <div class="container">
    <h1>Trouvez votre futur vinyle...</h1>
    <div class="simple_form search w-50">
      <%= form_with url: vinyls_path, method: :get, class: "d-flex search-form-control form-group" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control string required ",
          placeholder: "Recherche un vinyle..."
        %>
        <%= submit_tag "Soumettre", class:"button" %>
      <% end %>
    </div>
  </div>
</div>



<div class= "container mt-4 mb-4">
  <div class="row row-cols-1 row-cols-md-4 g-4">
      <% @vinyls.each do |vinyl| %>
        <div class="col">
            <%= render vinyl %>
        </div>
      <% end %>
  </div>
</div>

<br>
<br>

app/views/vinyls/show.html.erb
<div class="d-flex align-items-center mt-3 container">
  <i class="fa-solid fa-arrow-left"></i>
  <a><%= link_to "Retour", vinyls_path, class: "btn btn-retour " %></a>
</div>

<div class="container d-flex justify-content-evenly, align-items-center">
  <div class="container mt-5 mb-5">
    <div class="card shadow">
      <div>
        <%= image_tag @vinyl.photo_url, class:"vinyl_image" unless @vinyl.photo_url.nil? %>
      </div>
      <div class="text px-4 pb-4 flex-fill">
        <div class="vinyl-title">
          <p class="fw-bold m-0">
          <%= @vinyl.title %>
          </p>
        </div>
        <p>
          <%= @vinyl.artist.name %>, <em><%= @vinyl.year %></em>
        </p>
      </div>
    </div>
  </div>

  <div class="container", style="width: 200%; height: 480px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_TOKEN'] %>">
  </div>
</div>

<div class="container">
  <% if @users_vinyls.count == 1 %>
    <h3>Une personne possède ce vinyle</h3>
    <% elsif @users_vinyls.count > 1 %>
    <h4><%=@users_vinyls.count%> personnes possèdent ce vinyle</h4>
  <% end %>
    <% @users_vinyls.each do |users_vinyl| %>
      <div class="card card-want m-2 mb-3 p-3" >
        <div class="d-flex justify-content-space-around align-items-center p-3">
          <%= image_tag "https://res.cloudinary.com/dvw6upciw/image/upload/v1670444837/avatar_e5p5i5.webp", :width=>50, :height=>50%>
          <p class= "px-2 m-0"><%= users_vinyl.user.first_name.capitalize %></p>

          <a><%= link_to 'Je le veux', new_users_vinyl_exchange_path(users_vinyl), class: "btn btn-info" %></a>
        </div>
      </div>
    <% end %>
</div>

app/views/vinyls/vinyl.html.erb
<h1> hello </h1>