config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    resources :wishlists, only: [:create]
  end

  root to: "pages#home"

  resources :exchanges, only: [:show, :update] do
    resources :messages, only: :create
    member do
      post :complete_exchange
    end
  end

  resources :vinyls, only: [:index, :show] do
    # resources :exchanges, only: [:index]
    # resources :collections_vinyls, only: [:create, :new] # Ceci sont les anciennes routes, il faudrait prendre ceux de users_vinyls à la place
    resources :users_vinyls, only: [:create, :new, :update]
  end

  resources :collections, only: [:new, :create, :show, :index]

  resources :collections_vinyls, only: [:destroy]

  resources :users_vinyls, only: [] do
    resources :exchanges, only: [:new, :create]
    resources :collections_vinyls, only: [:create]
  end

  resources :wishlists, only: [:destroy]

  get "my-exchanges", to: "exchanges#index"
  patch "exchanges/:id/status", to: "exchanges#update_status"
  patch "exchanges/:id/offered_vinyl", to: "exchanges#update_offered_vinyl"
  get "vinyls-to-exchange", to: "collections#vinyls_to_exchange"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Fait avec <i class="fas fa-heart"></i> par la Groovy Team
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dvw6upciw/image/upload/v1670444845/logo_xuvssx.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dvw6upciw/image/upload/v1671039702/114935320_fckeey.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <a class="nav-link" href="#" data-bs-toggle="dropdown"></a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mes collections", collections_path, class: "dropdown-item" %>
              <%= link_to "Mes échanges", my_exchanges_path, class: "dropdown-item" %>
              <%= link_to "Déconnection", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connection", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>